//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:39:11 PM CST 
//


package org.globus.crux.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authzChain complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authzChain">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bootstrapPips" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="pips" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="pdps" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="combiningAlg" type="{http://www.w3.org/2001/XMLSchema}string" default="PermitOverride" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authzChain", propOrder = {
    "bootstrapPips",
    "pips",
    "pdps"
})
public class AuthzChain {

    protected Object bootstrapPips;
    protected Object pips;
    protected Object pdps;
    @XmlAttribute
    protected String combiningAlg;

    /**
     * Gets the value of the bootstrapPips property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBootstrapPips() {
        return bootstrapPips;
    }

    /**
     * Sets the value of the bootstrapPips property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBootstrapPips(Object value) {
        this.bootstrapPips = value;
    }

    /**
     * Gets the value of the pips property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPips() {
        return pips;
    }

    /**
     * Sets the value of the pips property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPips(Object value) {
        this.pips = value;
    }

    /**
     * Gets the value of the pdps property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPdps() {
        return pdps;
    }

    /**
     * Sets the value of the pdps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPdps(Object value) {
        this.pdps = value;
    }

    /**
     * Gets the value of the combiningAlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombiningAlg() {
        if (combiningAlg == null) {
            return "PermitOverride";
        } else {
            return combiningAlg;
        }
    }

    /**
     * Sets the value of the combiningAlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombiningAlg(String value) {
        this.combiningAlg = value;
    }

}
