//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:39:11 PM CST 
//


package org.globus.crux.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for certKeyFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="certKeyFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="key-file" type="{http://www.globus.org/security/descriptor/container}valStringType"/>
 *         &lt;element name="cert-file" type="{http://www.globus.org/security/descriptor/container}valStringType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "certKeyFileType", propOrder = {

})
public class CertKeyFileType {

    @XmlElement(name = "key-file", required = true)
    protected ValStringType keyFile;
    @XmlElement(name = "cert-file", required = true)
    protected ValStringType certFile;

    /**
     * Gets the value of the keyFile property.
     * 
     * @return
     *     possible object is
     *     {@link ValStringType }
     *     
     */
    public ValStringType getKeyFile() {
        return keyFile;
    }

    /**
     * Sets the value of the keyFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValStringType }
     *     
     */
    public void setKeyFile(ValStringType value) {
        this.keyFile = value;
    }

    /**
     * Gets the value of the certFile property.
     * 
     * @return
     *     possible object is
     *     {@link ValStringType }
     *     
     */
    public ValStringType getCertFile() {
        return certFile;
    }

    /**
     * Sets the value of the certFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValStringType }
     *     
     */
    public void setCertFile(ValStringType value) {
        this.certFile = value;
    }

}
