//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:39:11 PM CST 
//

package org.globus.crux.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credential" type="{http://www.globus.org/security/descriptor/container}credentialType" minOccurs="0"/>
 *         &lt;element name="adminAuthzChain" type="{http://www.globus.org/security/descriptor/container}authzChain" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/security/descriptor/container}defaultAuthzParam" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/security/descriptor/container}reject-limited-proxy" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/security/descriptor/container}context-lifetime" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/security/descriptor/container}replay-attack-window" minOccurs="0"/>
 *         &lt;element ref="{http://www.globus.org/security/descriptor/container}replay-attack-filter" minOccurs="0"/>
 *         &lt;element name="context-timer-interval" type="{http://www.globus.org/security/descriptor/container}valIntType" minOccurs="0"/>
 *         &lt;element name="replay-timer-interval" type="{http://www.globus.org/security/descriptor/container}valIntType" minOccurs="0"/>
 *         &lt;element name="trustedCertificates" type="{http://www.globus.org/security/descriptor/container}valStringType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "containerId", "credential", "adminAuthzChain", "defaultAuthzParam", "rejectLimitedProxy",
		"replayAttackWindow", "replayAttackFilter", "replayTimerInterval", "trustedCertificates" })
@XmlRootElement(name = "containerSecurityConfig")
public class ContainerSecurityConfig {

	@XmlElement(name="containerId")
	protected String containerId;
	protected CredentialType credential;
	protected AuthzChain adminAuthzChain;
	protected DefaultAuthzParam defaultAuthzParam;
	@XmlElement(name = "reject-limited-proxy")
	protected boolean rejectLimitedProxy;
	@XmlElement(name = "replay-attack-window")
	protected int replayAttackWindow;
	@XmlElement(name = "replay-attack-filter")
	protected boolean replayAttackFilter;
	@XmlElement(name = "replay-timer-interval")
	protected int replayTimerInterval;
	protected String trustedCertificates;

	
	
	public String getContainerId() {
		return containerId;
	}

	public void setContainerId(String containerId) {
		this.containerId = containerId;
	}

	/**
	 * Gets the value of the credential property.
	 * 
	 * @return possible object is {@link CredentialType }
	 * 
	 */
	public CredentialType getCredential() {
		return credential;
	}

	/**
	 * Sets the value of the credential property.
	 * 
	 * @param value
	 *            allowed object is {@link CredentialType }
	 * 
	 */
	public void setCredential(CredentialType value) {
		this.credential = value;
	}

	/**
	 * Gets the value of the adminAuthzChain property.
	 * 
	 * @return possible object is {@link AuthzChain }
	 * 
	 */
	public AuthzChain getAdminAuthzChain() {
		return adminAuthzChain;
	}

	/**
	 * Sets the value of the adminAuthzChain property.
	 * 
	 * @param value
	 *            allowed object is {@link AuthzChain }
	 * 
	 */
	public void setAdminAuthzChain(AuthzChain value) {
		this.adminAuthzChain = value;
	}

	/**
	 * Gets the value of the defaultAuthzParam property.
	 * 
	 * @return possible object is {@link DefaultAuthzParam }
	 * 
	 */
	public DefaultAuthzParam getDefaultAuthzParam() {
		return defaultAuthzParam;
	}

	/**
	 * Sets the value of the defaultAuthzParam property.
	 * 
	 * @param value
	 *            allowed object is {@link DefaultAuthzParam }
	 * 
	 */
	public void setDefaultAuthzParam(DefaultAuthzParam value) {
		this.defaultAuthzParam = value;
	}

	/**
	 * Gets the value of the rejectLimitedProxy property.
	 * 
	 * @return possible object is {@link ValBooleanType }
	 * 
	 */
	public boolean getRejectLimitedProxy() {
		return rejectLimitedProxy;
	}

	/**
	 * Sets the value of the rejectLimitedProxy property.
	 * 
	 * @param value
	 *            allowed object is {@link ValBooleanType }
	 * 
	 */
	public void setRejectLimitedProxy(boolean value) {
		this.rejectLimitedProxy = value;
	}

	/**
	 * Gets the value of the replayAttackWindow property.
	 * 
	 * @return possible object is {@link ValIntType }
	 * 
	 */
	public int getReplayAttackWindow() {
		return replayAttackWindow;
	}

	/**
	 * Sets the value of the replayAttackWindow property.
	 * 
	 * @param value
	 *            allowed object is {@link ValIntType }
	 * 
	 */
	public void setReplayAttackWindow(int value) {
		this.replayAttackWindow = value;
	}

	/**
	 * Gets the value of the replayAttackFilter property.
	 * 
	 * @return possible object is {@link ValBooleanType }
	 * 
	 */
	public boolean getReplayAttackFilter() {
		return replayAttackFilter;
	}

	/**
	 * Sets the value of the replayAttackFilter property.
	 * 
	 * @param value
	 *            allowed object is {@link ValBooleanType }
	 * 
	 */
	public void setReplayAttackFilter(boolean value) {
		this.replayAttackFilter = value;
	}

	/**
	 * Gets the value of the replayTimerInterval property.
	 * 
	 * @return possible object is {@link ValIntType }
	 * 
	 */
	public int getReplayTimerInterval() {
		return replayTimerInterval;
	}

	/**
	 * Sets the value of the replayTimerInterval property.
	 * 
	 * @param value
	 *            allowed object is {@link ValIntType }
	 * 
	 */
	public void setReplayTimerInterval(int value) {
		this.replayTimerInterval = value;
	}

	/**
	 * Gets the value of the trustedCertificates property.
	 * 
	 * @return possible object is {@link ValStringType }
	 * 
	 */
	public String getTrustedCertificates() {
		return trustedCertificates;
	}

	/**
	 * Sets the value of the trustedCertificates property.
	 * 
	 * @param value
	 *            allowed object is {@link ValStringType }
	 * 
	 */
	public void setTrustedCertificates(String value) {
		this.trustedCertificates = value;
	}

}
