//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:39:11 PM CST 
//


package org.globus.crux.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credentialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="credentialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="proxy-file" type="{http://www.globus.org/security/descriptor/container}valStringType" minOccurs="0"/>
 *         &lt;element name="cert-key-files" type="{http://www.globus.org/security/descriptor/container}certKeyFileType" minOccurs="0"/>
 *         &lt;element name="keyStore" type="{http://www.globus.org/security/descriptor/container}keyStoreType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "credentialType", propOrder = {
    "proxyFile",
    "certKeyFiles",
    "keyStore"
})
public class CredentialType {

    @XmlElement(name = "proxy-file")
    protected ValStringType proxyFile;
    @XmlElement(name = "cert-key-files")
    protected CertKeyFileType certKeyFiles;
    protected KeyStoreType keyStore;

    /**
     * Gets the value of the proxyFile property.
     * 
     * @return
     *     possible object is
     *     {@link ValStringType }
     *     
     */
    public ValStringType getProxyFile() {
        return proxyFile;
    }

    /**
     * Sets the value of the proxyFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValStringType }
     *     
     */
    public void setProxyFile(ValStringType value) {
        this.proxyFile = value;
    }

    /**
     * Gets the value of the certKeyFiles property.
     * 
     * @return
     *     possible object is
     *     {@link CertKeyFileType }
     *     
     */
    public CertKeyFileType getCertKeyFiles() {
        return certKeyFiles;
    }

    /**
     * Sets the value of the certKeyFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertKeyFileType }
     *     
     */
    public void setCertKeyFiles(CertKeyFileType value) {
        this.certKeyFiles = value;
    }

    /**
     * Gets the value of the keyStore property.
     * 
     * @return
     *     possible object is
     *     {@link KeyStoreType }
     *     
     */
    public KeyStoreType getKeyStore() {
        return keyStore;
    }

    /**
     * Sets the value of the keyStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeyStoreType }
     *     
     */
    public void setKeyStore(KeyStoreType value) {
        this.keyStore = value;
    }

}
