//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:39:11 PM CST 
//


package org.globus.crux.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.globus.crux.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReplayAttackFilter_QNAME = new QName("http://www.globus.org/security/descriptor/container", "replay-attack-filter");
    private final static QName _ReplayAttackWindow_QNAME = new QName("http://www.globus.org/security/descriptor/container", "replay-attack-window");
    private final static QName _ContextLifetime_QNAME = new QName("http://www.globus.org/security/descriptor/container", "context-lifetime");
    private final static QName _RejectLimitedProxy_QNAME = new QName("http://www.globus.org/security/descriptor/container", "reject-limited-proxy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.globus.crux.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthzChain }
     * 
     */
    public AuthzChain createAuthzChain() {
        return new AuthzChain();
    }

    /**
     * Create an instance of {@link AnyType }
     * 
     */
    public AnyType createAnyType() {
        return new AnyType();
    }

    /**
     * Create an instance of {@link ValBooleanType }
     * 
     */
    public ValBooleanType createValBooleanType() {
        return new ValBooleanType();
    }

    /**
     * Create an instance of {@link BootstrapPips }
     * 
     */
    public BootstrapPips createBootstrapPips() {
        return new BootstrapPips();
    }

    /**
     * Create an instance of {@link ValIntType }
     * 
     */
    public ValIntType createValIntType() {
        return new ValIntType();
    }

    /**
     * Create an instance of {@link DefaultAuthzParam }
     * 
     */
    public DefaultAuthzParam createDefaultAuthzParam() {
        return new DefaultAuthzParam();
    }

    /**
     * Create an instance of {@link ValStringType }
     * 
     */
    public ValStringType createValStringType() {
        return new ValStringType();
    }

    /**
     * Create an instance of {@link ContainerSecurityConfig }
     * 
     */
    public ContainerSecurityConfig createContainerSecurityConfig() {
        return new ContainerSecurityConfig();
    }

    /**
     * Create an instance of {@link CertKeyFileType }
     * 
     */
    public CertKeyFileType createCertKeyFileType() {
        return new CertKeyFileType();
    }

    /**
     * Create an instance of {@link Pdps }
     * 
     */
    public Pdps createPdps() {
        return new Pdps();
    }

    /**
     * Create an instance of {@link Interceptor }
     * 
     */
    public Interceptor createInterceptor() {
        return new Interceptor();
    }

    /**
     * Create an instance of {@link Pips }
     * 
     */
    public Pips createPips() {
        return new Pips();
    }

    /**
     * Create an instance of {@link CredentialType }
     * 
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link KeyStoreType }
     * 
     */
    public KeyStoreType createKeyStoreType() {
        return new KeyStoreType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValBooleanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/security/descriptor/container", name = "replay-attack-filter")
    public JAXBElement<ValBooleanType> createReplayAttackFilter(ValBooleanType value) {
        return new JAXBElement<ValBooleanType>(_ReplayAttackFilter_QNAME, ValBooleanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValIntType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/security/descriptor/container", name = "replay-attack-window")
    public JAXBElement<ValIntType> createReplayAttackWindow(ValIntType value) {
        return new JAXBElement<ValIntType>(_ReplayAttackWindow_QNAME, ValIntType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValIntType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/security/descriptor/container", name = "context-lifetime")
    public JAXBElement<ValIntType> createContextLifetime(ValIntType value) {
        return new JAXBElement<ValIntType>(_ContextLifetime_QNAME, ValIntType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValBooleanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.globus.org/security/descriptor/container", name = "reject-limited-proxy")
    public JAXBElement<ValBooleanType> createRejectLimitedProxy(ValBooleanType value) {
        return new JAXBElement<ValBooleanType>(_RejectLimitedProxy_QNAME, ValBooleanType.class, null, value);
    }

}
